apiVersion: v1
baseDomain: mysqllab.com
metadata:
  name: okdk8s
controlPlane:
  name: master
  replicas: 1
  hyperthreading: Enabled
  architecture: amd64
compute:
- name: worker
  replicas: 0
  hyperthreading: Enabled
  architecture: amd64
networking:
  networkType: OVNKubernetes
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  serviceNetwork:
  - 172.30.0.0/16
  machineNetwork:
  - cidr: 10.0.30.0/24
platform:
  none: {}
pullSecret: '<pull_secret>'
sshKey: |
  <ssh_key>
bootstrapInPlace:
  installationDisk: /dev/sda
