kind: AgentConfig
metadata:
  name: okdk8s
rendezvousIP: 10.0.30.50
hosts:
- hostname: okd01
  interfaces:
  - name: ens3
    macAddress: "52:54:00:12:34:56"
  networkConfig:
    interfaces:
    - name: ens3
      type: ethernet
      state: up
      ipv4:
        enabled: true
        address:
        - ip: 10.0.30.50
          prefix-length: 24
        dhcp: false
    dns-resolver:
      config:
        server:
        - 10.0.30.1
    routes:
      config:
      - destination: 0.0.0.0/0
        next-hop-address: 10.0.30.1
        next-hop-interface: ens3
        table-id: 254
